#!/bin/bash
#
# https://github.com/cirruslabs/cirrus-ci-web/blob/master/schema.gql
#
# https://cirrus-ci.com/explorer
#
set -e

credits=$(curl -s -X POST --data '{"query": "query { ownerInfoByName(platform: \"github\", name: \"containers\") { balanceInCredits }}"}}' https://api.cirrus-ci.com/graphql | jq -r .data.ownerInfoByName.balanceInCredits)

echo $credits

# If running from cron, log history
if ! [[ -t 0 ]]; then
    log=/home/esm/.cirrus-credits/history.csv
    printf "\"%s\", %s\n" "$(date --iso-8601=seconds)" $credits >>$log
fi

# Warn
min=30
x=$(bc <<< "$credits < $min")
if [[ $x -eq 1 ]]; then
    mail -s "DANGER! Cirrus credits <$min!" esm <<<"Credits: $credits"
fi
